version: "3"

services:
    hivegame:
        build:
            context: ./hive
        ports:
            - "8000:8080"
        depends_on:
            - db
        command: php -S 0.0.0.0:8080 -t src/
        networks:
            - hive-network
        environment:
            - DB_HOST=db
        extra_hosts:
            - "host.docker.internal:host-gateway"

    db:
        build:
            context: ./db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=hive
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - hive-data:/var/lib/mysql
        networks:
            - hive-network

    ai:
        build:
            context: ./ai
        ports:
            - "5000:5000"
        networks:
            - hive-network


    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8081:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home
        networks:
            - test-network

    sonarqube:
        image: sonarqube:latest
        ports:
            - "9001:9000"
        volumes:
            - sonarqube-data:/opt/sonarqube/data
        networks:
            - test-network

volumes:
    jenkins-data:
    sonarqube-data:
    sonar_db-data:
    hive-data:

networks:
    test-network:
    hive-network: